version: "3.4"
services:
  dev:
    container_name: cybics-software
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - HOST_UID=$HOST_UID
      - HOST_GID=$HOST_GID
      - HOST_DOCKER_GID=$HOST_DOCKER_GID
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - ../../.dev.env
      - ../../.env
    volumes:
      - ../../:/CybICS
      - ~/.ssh:/home/devuser/.ssh/
      - ~/.gitconfig:/home/devuser/.gitconfig
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKER_ENV_DIR/.bash_history:/home/devuser/.bash_history
  registry:
    container_name: cybics-registry
    image: registry:2
    ports:
      - 5000:5000
