version: "3.4"
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../../../:/CybICS
      - ~/.ssh:/home/devuser/.ssh/
      - ~/.gitconfig:/home/devuser/.gitconfig

