version: "3.4"
services:
  dev:
    container_name: cybics-stm32
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../../.dev.env
      - ../../.env
    volumes:
      - ../../:/CybICS
      - ~/.ssh:/home/docker/.ssh/
      - ~/.gitconfig:/home/docker/.gitconfig
    user: ${HOST_UID:-1000}:${HOST_UID:-1000}
