# This workflow will test with flawfinder

name: flawFinder C

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flawfinder:
    name: Flawfinder

    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3        

      - name: Flawfinder scan
        run: flawfinder --html --context --minlevel=1 ./software/  > flawfinder-report.html

      - name: Upload analysis results
        uses: actions/upload-artifact@v3
        with:
          name: Archive production artifacts
          path: flawfinder-report.html
          retention-days: 90
