name: KiBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  schema: "hardware/*.kicad_sch"
  board: "hardware/*.kicad_pcb"
  dir: "hardware/"
  config: "hardware/kibot.yaml"

jobs:
# checks
  ERC:
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki7
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc -v -i
          
  DRC:
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki7
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc -v -i
