name: KiBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  schema: "hardware/*.kicad_sch"
  board: "hardware/*.kicad_pcb"
  dir: "hardware/"
  config: "hardware/kibot.yaml"

jobs:
# checks
  ERC:
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki7
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc -v -i
          
  DRC:
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki7
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc -v -i
          
  # images
  render:
    runs-on: ubuntu-latest
    needs: [DRC]
    container:
      image: setsoft/kicad_auto:ki7
    steps:
      - uses: actions/checkout@v3
      - name: run kibot
        run: | 
          kibot -c ${{env.config}} -e ${{env.schema}} -b ${{env.board}} -d ${{env.dir}} -s run_erc,run_drc -v \
            board_black_top.svg board_black_bottom.svg
      - uses: actions/upload-artifact@v3.1.1
        if: ${{success()}}
        with:
          name: ${{github.event.repository.name}}_img
          if-no-files-found: error
          path: |
            ${{env.dir}}/img/**
            !${{env.dir}}/**/*.ogv
            !${{env.dir}}/**/*.log

  # Push changes back
  push_back:
    runs-on: ubuntu-latest
    needs: [render]
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: stefanzweifel/git-auto-commit-action@v5
