name: KiBot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  schema: "hardware/*.kicad_sch"
  board: "hardware/*.kicad_pcb"
  dir: "hardware/"

jobs:
# checks
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        # Required - kibot config file
        config: hardware/kibot.yaml
        dir: Generated
        skip: run_drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ERC_Output
        path: Generated


  DRC:
    runs-on: ubuntu-latest
    needs: ERC

    steps:
    - uses: actions/checkout@v3

    - name: Run DRC
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        # Required - kibot config file
        config: hardware/kibot.yaml
        dir: Generated
        skip: run_erc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: DRC_Output
