name: KiCad schematic

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.3.1
      with:
      # Required - kibot config file
        config: any.kibot.yaml
      # optional - prefix to output defined in config
        dir: docs
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'
      # optional - verbose output info
        verbose: 0
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs
